USE codeup_test_db;

DROP TABLE IF EXISTS albums;

CREATE TABLE IF NOT EXISTS albums (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
Artist VARCHAR(100) NOT NULL,
record_name VARCHAR(50),
release_date INT,
sales DOUBLE,
genre VARCHAR(50),
PRIMARY KEY (id)
);